### ISSUE TITLE
Function authors

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#12]
Ramiro, in ?ProfoundData, it says

Author(s) Except where indicated otherwise, the functions in this package were written by Ramiro Silveyra Gonzalez.

This feels inconsistent to me - it would be logical to have here the package authors, and why not just add your author tag to every function you wrote?

**Comment by christopherreyer** [comment]
am i actually entitled to be an author if I did not write any line of code or so? I think I did think/discuss quite a bit about the package with Ramiro but I did not do any "real" work. just to be sure... Of course I would like to be an author but I do not want to violate any code of ethics or so from cran.

**Comment by florianhartig** [comment]
Well, we can discuss this again, but I would say authors are those that have created the package, which I would view not only as writing the code, but also the initial idea, design, feedback etc., similar to a paper. Contributors are those that contributed smaller chunks of code or fixes. 

But it is of course true that Ramiro did most of the work, which, however, I think is reflected in him being the maintainer. But we can maybe discuss it again internally.

**Comment by christopherreyer** [comment]
ok, thanks. @Rasilgon please let me know if you think my contribution was not substantial enough.
