### ISSUE TITLE
vigenette Database citation

### ISSUE THREAD

**Issue by Rasilgon** [COST-FP1304-PROFOUND/ProfoundData#13]
The vignette has the following statement.

> Please cite the work as follows:
> 
> Reyer, CPO et al. (2018) The PROFOUND Database for evaluating vegetation models and simulating climate impacts on forest stands. Submitted to Earth System Science Data XXX:XXX-XXX. License: CC-BY-NC-4.0.
> 
> Reyer, CPO et al. (2018) The PROFOUND Database. Data Repository: GFZ-Data Services. DOI:XXX. License: CC-BY-NC-4.0.

Should this be removed from the vignette? Or should it be updated?

**Comment by christopherreyer** [comment]
I have written a suggestion how to write the data statement in the checklist document

**Comment by florianhartig** [comment]
I will move this to a real citatation

**Comment by florianhartig** [comment]
Speaking about the vignettes - where are they located?

**Comment by florianhartig** [comment]
Sorry, found it - data-raw

**Comment by florianhartig** [comment]
done
