### ISSUE TITLE
downloadDatabase file selection does not work under Windows

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#16]

**Comment by Rasilgon** [comment]
Is this solved?

**Comment by florianhartig** [comment]
I don't think so. Do you have a windows computer to check?

**Comment by mmahnke** [comment]
Hi guys, I just tested the downloadDatabase function in Windows and everything worked fine. Window opens for directory definition, download and unzipping also work fine if the "setsd(setwd(location))" is changed. Is "setsd" a typo or a function I do not know?

**Comment by Rasilgon** [comment]
In ubuntu, the downloading  works (not unzipping) and also  throws a message about "setsd".

> > downloadDatabase()
> trying URL 'http://www.pik-potsdam.de/data/doi/10.5880/PIK.2019.008/ProfoundData.zip'
> Content type 'application/zip' length 2796739590 bytes (2667.2 MB)
> ==================================================
> downloaded 2667.2 MB
> 
> dowload successfull, trying to unzip. This may not work on some operating systems. In this case, unzip by hand.
> Error in downloadDatabase() : could not find function "setsd"

**Comment by florianhartig** [comment]
OK, I think there are two potential issues

a) The main problem was the platform-independent query to the user to choose a file directory. This didn't work for Mats under Windows, but it does for Ramiro now. I'm not sure, this just doesn't seem to be particularly stable

b) The second issue is that unzipping the file may create some problems in some operation systems that may not have unzip, or a different version of unzip installed.

I think b is not really an issue, as it is already wrapped in try statements and throws a useful error message. 

Regarding a) - for now, I have removed the option of a graphical query for the file location, and set the default (if file location is not provided) on current wd.

I'll consider this closed
