### ISSUE TITLE
Update vignettes 

### ISSUE THREAD

**Issue by Rasilgon** [COST-FP1304-PROFOUND/ProfoundData#19]
Current vignette does not explain the downloadDatabase function and any other modification made since v 0.2.0

**Comment by florianhartig** [comment]
I have added downloadDatabase - is there anything other to add?

**Comment by matsmahnken** [comment]
After talking to @Rasilgon we think that at the moment we have nothing to add. We need to run the _data-raw/ProfoundData.Rmd_ to update the vignettes, right?

**Comment by florianhartig** [comment]
Hi Mats,

yes, if you could do this that would be good, can be closed afterwards

**Comment by matsmahnken** [comment]
Yes, I will do that after we have the new DB version ready - so hopefully in the next days.

**Comment by florianhartig** [comment]
I will updated the vignettes for the 0.2.1 CRAN release now ... Mats, if you have time, for the 0.2.2 release, could you maybe also have a look at the vignettes wrt readability / completeness?

**Comment by matsmahnken** [comment]
The rmd files for the vignettes are checked for typos and new vignette htmls are produced with the new DB version 0.3 including new DOI links. See 3dfa079142654780a9bb74da8cca3754bf0c4f26. New DOI links will only work in from the next days onwards - the new DOI is to be registered in the next days.
