### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#20]
There are various TODOs, mostly regarding missing help items. Can someone search in files and close this for the 0.2.1 release?

**Comment by matsmahnken** [comment]
Filled the TODO help items to the best of my knowledge in #22 .

There are still some TODOs for checks in _PROFOUND database/createDB/_.

Also there is one TODO in _PROFOUND database/Processing/ProfoundOtherData_check.R_ I don't know how to handle.

**Comment by florianhartig** [comment]
Are these regarding documentation or code?

**Comment by matsmahnken** [comment]
The open TODOs specify code that should be included. e.g `TODO if something missing stop it`

**Comment by matsmahnken** [comment]
@Rasilgon mentioned that the "TODOs" left in the code can be removed so I discarded all of them (see #24). There should be no "TODOs" left in ProfoundData.
