### ISSUE TITLE
Finalize 0.2.1 release

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#23]
I think we should finalize the 0.2.1 release, and maybe also use this as an opportunity to push the package to CRAN. 

TODO: close all issues currently associated with https://github.com/COST-FP1304-PROFOUND/ProfoundData/milestone/1

Anything else?

**Comment by matsmahnken** [comment]
I agree. It would be great to also have the new version of the DB ready by then.

@Rasilgon proposed to open a develop-branch after the next release for further work.

**Comment by florianhartig** [comment]
In my other projects, I see CRAN as the stable branch, and GitHub basically as develop, and thus only create feature branches. We have tested out the standard branch model a few times, but found the parallel dev / stable model to be mostly redundant in the end. So, I would recommend feature branches that are merged back when the features are implemented, and hotfixes directly in the master. But happy to try out other things.

**Comment by florianhartig** [comment]
Hi guys, I have reverted the latest changes that were made for the new (unpublished) DB structure, and am currently preparing to finalize this and push it to CRAN. 

@Rasilgon - as I upload it to CRAN, I have changed myself to cre status, there is unfortunately no difference between creator and maintainer, and I think it would be impractical if you maintain (unless you say you have the time)

However, I have added a line in the main help file of the package, stating that 

> Except where indicated otherwise, the functions in this package were written by Ramiro Silveyra Gonzalez, Christopher Reyer, Florian Hartig and Mahnken. Ramiro Silveyra Gonzalez was the main developer of the package. Florian Hartig is currently the maintainer.

OK for everyone?

**Comment by florianhartig** [comment]
fyi, I have submitted the package to CRAN

**Comment by christopherreyer** [comment]
Thanks @florianhartig for submitting the package and I agree with you ebing the maintainer. thanks a lot!

**Comment by florianhartig** [comment]
OK, this was a bit messy, but the package is now on CRAN https://cran.r-project.org/web/packages/ProfoundData/index.html
