### ISSUE TITLE
global radiation unit "rad_Jcm2day" to "rad_Jcm2"

### ISSUE THREAD

**Issue by matsmahnken** [COST-FP1304-PROFOUND/ProfoundData#26]
Hi guys, @christopherreyer and Stefan Lange from PIK identified that the unit of global radiation we have in the DB is not very consistent with other variable units and can thus be a bit confusing - but is not per se incorrect.

At the moment we have "rad_Jcm2day" and "J cm-2 day-1" in the DB but since the global radiation is given on a daily time resolution the variable name should be reduced to "rad_Jcm2". Comparing to precipitation which is "p_mm" in the DB where P is also given in a daily resolution - we also would not define the unit "p_mmday" as in "P mm day-1".
"rad_Jcm2day" also produces confusion when it is aggregated to annual values by summing up. Then the variable is still named "rad_Jcm2day" although it should be "rad_Jcm2".

Summarizing, we propose to change all "rad_Jcm2day" and related metadata "J cm-2 day-1" entries to "rad_Jcm2" and "J cm-2" respectively. Do you agree?
I have prepared some commits that could do this job.

**Comment by matsmahnken** [comment]
#27 has the linked commits in it in order to change the variable name in the DB itself and in the package. For the package the renaming is important for the _summarizeData()_ function.

**Comment by florianhartig** [comment]
Should be solved with https://github.com/COST-FP1304-PROFOUND/ProfoundData/commit/ba4728ba3f96d4a12fe77f400e7dc0107bc43ce7

**Comment by matsmahnken** [comment]
We need to re-commit the changes for the rad_Jcm2 changes in the package so that it will be fully compatible with the new DB version. How do we best re-commit https://github.com/COST-FP1304-PROFOUND/ProfoundData/commit/ba4728ba3f96d4a12fe77f400e7dc0107bc43ce7?

**Comment by matsmahnken** [comment]
These changes are re-commited in branch 0.3.0 and will be included in the new release.
