### ISSUE TITLE
doi in database

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#28]
There is an issue for CRAN with a data citation that is in the sql database

```
Found the following (possibly) invalid URLs:
  URL: doi:10.1073/pnas.1312330110
    From: inst/doc/PROFOUNDdatabase.html
    Message: Invalid URI scheme (use \doi for DOIs in Rd markup)
```

I am currently trying to find out if we can correct the formatting from R, or of this has to be changed in the db.

**Comment by florianhartig** [comment]
The problem is that this is a doi without https://doi.org/

A will correct this now by hand in the vignette, but would be good to correct this in the db for the 0.2.2 version

`
Based on climate data described here: Warszawski, L., Frieler, K., Huber, V., Piontek, F., Serdeczny, O., Schewe, (2013) The Inter-Sectoral Impact Model Intercomparison Project (ISI-MIP), Proceedings of the National Academy of Sciences,111,9, 3228-3232. <a href="doi:10.1073/pnas.1312330110" class="uri">doi:10.1073/pnas.1312330110</a>, <a href="https://www.isimip.org/gettingstarted/#input-data-bias-correction" class="uri">https://www.isimip.org/gettingstarted/#input-data-bias-correction</a></p></li>
`

**Comment by matsmahnken** [comment]
Will include this in the new sql DB version.

BTW, are we aiming for DB version 0.2.2 and skipping 0.2.1 to keep package and DB version numbering identical? Or are DB and package versions considered independent from each other?

**Comment by florianhartig** [comment]
Yes, I would keep the version number compatible. Maybe it would even be sensible to label database versions with 0.X, and R package updates with 0.X.X, which would mean that the next update is 0.3?

**Comment by matsmahnken** [comment]
I agree, to have the versions compatible but not necessarily identical. Following 0.X for the DB and 0.X.X we would assume to have more frequent package updates than DB updates which is sensible I think.

So the next DB version then is 0.3 and the next R package version is 0.3.0, is that right?

**Comment by matsmahnken** [comment]
The DOI in the new DB version 0.3 is corrected and should correctly point to the reference.
