### ISSUE TITLE
Stable landing page for database / doi

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#29]
We are currently linking to http://doi.org/10.5880/PIK.2019.008 for the database - is this the doi for the database version, or is this the doi for the website?

If this is for the db, what happens if we update the doi, i.e. are the old dois linking to the new version or the old one?

**Comment by christopherreyer** [comment]
this is the doi for the old database version, the new DOI will be http://doi.org/10.5880/PIK.2020.006

the landing page for the old DOI will link to the new landing page with the new doi.

**Comment by florianhartig** [comment]
OK, this should be fine
