### ISSUE TITLE
Non-standard files/directories found at top level

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#3]
```
Non-standard files/directories found at top level:
  ‘data-raw’ ‘ProfoundData.Rproj’checking R code for possible problems ... NOTE
```

@Rasilgon - I think the basic issue, also related to https://github.com/COST-FP1304-PROFOUND/ProfoundData/issues/2, is that data-raw should be added to the buildignore, right? See
https://stackoverflow.com/questions/41855970/non-standard-file-data-raw-note-on-building-checking-a-package-in-r

**Comment by Rasilgon** [comment]
Neither .gitignore nor .Rbuildignore are in the repo.

In my local files I have the exceptions, e.g..buildignore 

`^.*\.Rproj$`
`^\.Rproj\.user$`
`^data-raw$`

I must have forgotten to commit them.

**Comment by florianhartig** [comment]
they should be - but I wanted to redo the Rstudio project structure anyway (because the project should be in the root), so if you can solve https://github.com/COST-FP1304-PROFOUND/ProfoundData/issues/7 I can do the rest

**Comment by florianhartig** [comment]
This seems to be solved
