### ISSUE TITLE
inst/rmd files obsolte?

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#30]
I think this is mainly to @Rasilgon - are the Rmd files in inst/rmd obsolte? Looks to me like a previous version of the vignette.

**Comment by matsmahnken** [comment]
Isn't this used in _reportDB()_?

**Comment by florianhartig** [comment]
ah, maybe ... I forgot we had such a function. Hmm ... maybe. I wonder if it's necessary to have this on file, I guess one could also save it as a string / Rds in the package, but if it's used, let's just keep it there for the moment

**Comment by matsmahnken** [comment]
alright, then we keep it for now.
