### ISSUE TITLE
0.3.0 release (database update)

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#31]
btw., what's up with the 0.2.2 release - did you get the data update?

**Comment by florianhartig** [comment]
Correction - I think we said we would call a database update 0.3.0, right?

**Comment by christopherreyer** [comment]
yes, we are just preparing the new DB version 0.3. we have to submit the paper today but probably we will get an extension by a week or so.

**Comment by florianhartig** [comment]
Ah, nice! Yes, no problem, just wanted to know what the status is.

**Comment by matsmahnken** [comment]
Yes, right. We are preparing the new DB version 0.3. The data update from Soro is available and being included in the DB. I already have a new sqlite version and am now looking at the vignettes to see if the re-compilation worked and all the changes we want are in there to prepare everything for the new DOI.

**Comment by matsmahnken** [comment]
The new DB version will become available in the next days with the new DOI.

**Comment by matsmahnken** [comment]
The new DB version 0.3 is now released with a new DOI: http://doi.org/10.5880/PIK.2020.006

**Comment by florianhartig** [comment]
OK, so this can be closed, right?

**Comment by matsmahnken** [comment]
Yes, this is completely finished and can be closed.
