### ISSUE TITLE
new Soro data: TREE and STAND

### ISSUE THREAD

**Issue by matsmahnken** [COST-FP1304-PROFOUND/ProfoundData#34]
The new data we got for Soro are reconstructed single tree data which are included in the TREE table and derived stand data which are independently included in the STAND table. The conversion from the reconstructed single tree data to stand data is not straightforward as in the other sites because TREE is not a full inventory of the stand for all the years because of the applied reconstruction method.

The method how to derive the data in STAND from the data in TREE will be included in the SOM of the data paper. Also a note that TREE in Soro is not a full inventory and can not be used to derive stand-scale measures is included in the Soro stand description of the data paper as well as in the DB itself.

Nevertheless, the TREE table can and should not be used to derive stand-scale data with the _summarizeData()_ function because the method implemented here does not hold for this data.

It would be good to prevent the user to apply this function on the TREE dataset for Soro and throw an error. I am already looking for a solution for this.

**Comment by florianhartig** [comment]
Hi Mats, not sure if it is necessary to describe it in detail in the paper, as long as it is properly documented in the code for the creation of the databased, and possibly also in the database (I think there was a field to do comments, right?)

**Comment by florianhartig** [comment]
About the summarizeData function: my question would be - if it is not sensible to use the tree data, why provide it at all? Not providing it would automatically mean that it can't be misinterpreted. 

If we provide it, I would also allow the user to summarize it. Why not? Do we think there is a clear bias? If I understood you correctly, you don't want the user to use it, because you think the stand values are more accurate? Stil, I would throw at most a warning that the stand data should preferentially be used.

**Comment by matsmahnken** [comment]
Hi Florian. You are right, this is not an ideal solution. Christopher found a much better solution - provide the underlying original "raw" Soro data with the same DOI like the Profound DB. This way we keep the concept of the DB as we had it for the old data in Soro and keep the TREE and STAND data harmonized.

We wanted to include the other single tree data into the DB but the DB structure and the DB do not fit together, hence this way. This additional data is included because it may be interesting for some people but for most of the people the data in the DB will be better.

**Comment by matsmahnken** [comment]
This issue can be ignored since the new Soro data were included in the new DB version in the conventional way NOT following the suggestion in this issue. Soro STAND data are computed from Soro TREE data and _summarizeData()_ can be used without any problems.
