### ISSUE TITLE
Database hosting offline

### ISSUE THREAD

**Issue by lstrebel** [COST-FP1304-PROFOUND/ProfoundData#38]
Hi,

I was interested in checking out the Profound database, but it seems to me that the database is no longer hosted at the same address. I get the following error message, when trying to follow the instruction from the help page.

sqlfile = downloadDatabase()
trying URL 'http://www.pik-potsdam.de/data/doi/10.5880/PIK.2019.008/ProfoundData.zip'
Error in download.file("http://www.pik-potsdam.de/data/doi/10.5880/PIK.2019.008/ProfoundData.zip",  : 
  cannot open URL 'http://www.pik-potsdam.de/data/doi/10.5880/PIK.2019.008/ProfoundData.zip'
In addition: Warning message:
In download.file("http://www.pik-potsdam.de/data/doi/10.5880/PIK.2019.008/ProfoundData.zip",  :
  cannot open URL 'http://www.pik-potsdam.de/data/doi/10.5880/PIK.2019.008/ProfoundData.zip': HTTP status was '404 Not Found'

Is it possible the URL has changed? All the file links on https://dataservices.gfz-potsdam.de/pik/showshort.php?id=escidoc:2549901 seem to be offline.

Is the database still available somewhere?

Best regards,
Lukas

**Comment by christopherreyer** [comment]
Hi Lukas,
thanks for the note. 
yes, we also just discovered some days ago and we are looking into the issue. 
@matsmahnken can you maybe also post an update here once the files are online again?
bests
christopher

**Comment by lstrebel** [comment]
Hi Christopher,

Thanks for the quick reply and hope the issue can be resolved easily.

Best,
Lukas

**Comment by christopherreyer** [comment]
one more thought:
if you do not hear from in a week or so from now, we can try to send you the files through alternative pathways but let us focus a few days on fixing the issue. probably it is just a server issue or so, since we did not delete the files or anything like that. so just remind us when things get urgent for you.

**Comment by matsmahnken** [comment]
Hey Lukas and Christopher,

I am on it. Once it is resolved I will post here. If the issue takes more time we will transfer the database in other ways to you Lukas as Christopher suggests.

Best,
Mats

**Comment by matsmahnken** [comment]
Not sure why, but the database is online again. The problem resolved itself. Lukas, please let us know if it works for you too.

Best,
Mats

**Comment by lstrebel** [comment]
Hi Mats and Christopher,

Yes seems to work for me as well. Thank you!
