### ISSUE TITLE
Stand biomass Bily Kriz

### ISSUE THREAD

**Issue by Rasilgon** [COST-FP1304-PROFOUND/ProfoundData#39]
I have recently downloaded the package and  the database (December 2021).  The pkg version is 0.2.1, and the database, v0.2.0, according to the version table.

When checking stand biomass for several locations, I noticed that the values of biomass of bily_kriz are much lower than other sites. It looks as there might be some problems with the units. For instance, the values of stand biomass would make sense if they were Mg, instead of kg.

**Comment by matsmahnken** [comment]
Hi @Rasilgon, good to see the DB is in use. The issue with biomass units at bily_kriz has come up earlier already and we addressed it in the most current version of the DB (version 0.3) which can be found here: [https://dataservices.gfz-potsdam.de/pik/showshort.php?id=escidoc:5162892](https://dataservices.gfz-potsdam.de/pik/showshort.php?id=escidoc:5162892)

You can have a look at the changelog there to see what has changed to the version you are using at the moment:
"[...] STAND: corrected values for foliageBiomass_kgha, branchesBiomass_kgha, stemBiomass_kgha and rootBiomass_kgha for Bily Kriz to match unit [...]"

Let me know if this solves the issue or if there is another issue with the biomass unit at bily_kriz that we have not corrected yet.

**Comment by Rasilgon** [comment]
Great! Thanks, @matsmahnken,  for the quick answer! 
I downloaded the DB with pkg function *downloadDatabase*,  and assumed that it will give me the last version.  Good to know that is fixed, and thanks for doing it. Perhaps the pkg function needs to be updated.

**Comment by matsmahnken** [comment]
Alright, thanks for letting us know. Indeed the _downloadDatabase_ function should download the latest version. Once we close #36, we can publish the pkg version 0.3 and it should be working fine.

I'll close this issue for now.
