### ISSUE TITLE
possibly unsafe calls

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#4]
```
Found the following possibly unsafe calls:
File ‘ProfoundData/R/setDB.R’:
  assignInNamespace("db", db, pos = "package:ProfoundData")
```

@Rasilgon, what's the idea here / why was this necessary? The help of assignInNamespace flags this as hacky and advises:

> They should not be used in production code (except perhaps assignInMyNamespace, but see the ‘Note’).

Is there any other way to code whatever we're trying to do here?

**Comment by Rasilgon** [comment]
I found an alternative option which doesn't through notes/warnings/errors using options as described in https://cran.r-project.org/web/packages/settings/vignettes/settings.html

**Comment by florianhartig** [comment]
but could we do this without adding a new dependency? I think you want to use the settings package, right?

**Comment by Rasilgon** [comment]
I tried here and it works, I run local checks. I have already committed to see if TRAVIS runs clean.

Yes,  I guess we could avoid using the settings package.
What we need is:

-  setDB() creates/configures an object with the DB path and the DB driver (in this case sqlite)
- this object should be accessible to other package functions
- and not accessible to the user

**Comment by florianhartig** [comment]
Why shouldn't it be accessible to the user?

**Comment by Rasilgon** [comment]
It's should be accessible trough a function, so they modify or get the values. If the user access the object itself, there is are chance for errors which we do not handle.
