### ISSUE TITLE
Question about contributors

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#6]
Hi Ramiro / Christopher,

I saw you listed

            person("Klara", "Dolos", email = "dolos@kit edu", role = c("ctb")),
            person("Friedrich", "Bohn", email = "friedrich.bohn@ufz.de", role = c("ctb")),

of course they are on the paper, but did they actually contribute code to the package?

Also, what is

            person("Data", "Contributors",email = "contributor@data.com", role = c("ctb"))

**Comment by christopherreyer** [comment]
Hi Florian,
I do not know about Klara (she is not on my author list for the r-package) but as far as I remember, Friedrich provided the code for the conversion of ascii to netcdf. but Ramiro should know who really contributed.

**Comment by Rasilgon** [comment]
Hi, this what in issue to be solved. Originally we were all contributos and kept "data", "contributors" to remind us to add any other contirbutor that was not part of the initial team. 
I think now we can remove both "Data" and "Klara". She did contribute to prepare the DB but not the package in the end.

**Comment by KDolos** [comment]
I am here :-)! I contributed to devl. of the data base structure and added e.g. epsg codes, vegetation type, checked elevation etc. I did not write functions within the package.

**Comment by christopherreyer** [comment]
hi klara, good to hear from you!
yes, just to be clear and avoid misunderstandings:
you should be a co-author of the data paper (and of the database which get its own doi) which we will hopefully submit soon. but not for the R-Package. I hope this is fine with you!

**Comment by florianhartig** [comment]
We could list contributors to the db either on the to page of this [repository](https://github.com/COST-FP1304-PROFOUND/ProfoundData), or on the [subpage of the db](https://github.com/COST-FP1304-PROFOUND/ProfoundData/tree/master/PROFOUND%20database)

**Comment by christopherreyer** [comment]
yes, but there will also be a proper doi landing page where the database and the links to the paper etc. are and also the link tp the repository. so we can simply paste that link somewehre in github as well.

**Comment by florianhartig** [comment]
So, what about Friedrich?

In general, I think we should stick to the standards for R packages http://epub.wu.ac.at/3269/1/Report114.pdf

Which would mean that Ramiro, Christopher and I are author, Ramiro is creator = maintainer if he wants to, and Friedrich would be contributor

**Comment by christopherreyer** [comment]
I think friedrich wrote some of the functions for the netcdf-conversion. does that qualify him as author or contributor? I think either way is fine.
bests
christopher

**Comment by florianhartig** [comment]
If we used a small part of code from him, ctb is the usual acknowledgement

**Comment by christopherreyer** [comment]
ok, @Rasilgon can you confirm that he mostly send oyu some code for the conversion and that was it?

**Comment by Rasilgon** [comment]
Friedrich is the creator of the file writeNetCDF.R file. He wrote the functions and the documentation. I only did some small editing of the help file.

**Comment by florianhartig** [comment]
ok, then that's clear, and you are the cre?

**Comment by Rasilgon** [comment]
OK, then we (Christpoher, Florian and I) are authors, Friedrich a contributor and I am in the maintainer/creator.

**Comment by Rasilgon** [comment]
I have update the DESCRIPTION file accordingly.

**Comment by florianhartig** [comment]
solved with https://github.com/COST-FP1304-PROFOUND/ProfoundData/commit/26d1cfde94cd80bf74078e26ea9eb9b33e7d4462

@Rasilgon - you can automatically close issues with a commit that says something like "Fixes #6"
