### ISSUE TITLE
Capitalization / naming issues

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#7]
@Rasilgon - there are two files that are exist double, i.e.

* https://github.com/COST-FP1304-PROFOUND/ProfoundData/blob/master/PROFOUND%20database/Processing/sites.txt
* https://github.com/COST-FP1304-PROFOUND/ProfoundData/blob/master/PROFOUND%20database/createDB/SITEDESCRIPTION_to_DB.R

but with different capitalization - in my Unix system, this creates major problems, because those are recognized as the same files. 

Can you change this to unique filenames, so that I can clone the repo again? I could probably do it from GitHub, but I don't know if there are things that link to those files

**Comment by florianhartig** [comment]
the other file is still there though

**Comment by florianhartig** [comment]
@Rasilgon - could you rename the file? I can't properly work locally with the repo as long as this is unsolved, and I don't want to rename it without you checking if this breaks some other code

**Comment by Rasilgon** [comment]
Is the other file also a problem?

**Comment by florianhartig** [comment]
The file was still there though - I renamed now to https://github.com/COST-FP1304-PROFOUND/ProfoundData/blob/master/PROFOUND%20database/createDB/SITEDESCRIPTION_to_DB-2.R in https://github.com/COST-FP1304-PROFOUND/ProfoundData/commit/848f32517a17e3b41ab1fb30804a4fc380a728b1

Also for the sites file, a rename would have been sufficient.

**Comment by florianhartig** [comment]
Leaving this open for the file names to be resolved
