### ISSUE TITLE
Binaries in the repo

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#8]
There are html files committed to the repo (in particular the vignette), which is the reason why the repo size has blown up again - as soon as https://github.com/COST-FP1304-PROFOUND/ProfoundData/issues/7 is solved, I'll do a cleanup, but the repo file size is quite large again, I wonder if we should re-start the repo again?

There are also some weird data files, e.g. https://github.com/COST-FP1304-PROFOUND/ProfoundData/blob/master/ProfoundData/R/sysdata.rda ... is this a required file? Why is it in this folder?

**Comment by Rasilgon** [comment]
This is related to #4 . I replaced the code linked to the package data and removed the sysdata.
