### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by florianhartig** [COST-FP1304-PROFOUND/ProfoundData#9]
So what about this license file with the additions to GPL-3 https://github.com/COST-FP1304-PROFOUND/ProfoundData/blob/master/ProfoundData/LICENSE

Are we keeping this? I think I would tend to remove this, for simplicity - who's going to create derivatives of this highly specialized R package anyway?

**Comment by Rasilgon** [comment]
The file comes from rLPJGUESS. Orginally we had GPL-3 with modifications in rLPJGUESS and we thought that we could use the same license statement for ProfoundData. However, the issue was still open.
